export enum QueryKey {
  GET_ME = "GET_ME",
  GET_APP_VERSION = "GET_APP_VERSION",
  GET_HISTORY_POINTS = "GET_HISTORY_POINTS",
  GET_USER_ID = "GET_USER_ID",
  GET_DIARY = "GET_DIARY",
  GET_TASKS = "GET_TASKS",
  GET_TASKS_CREATED = "GET_TASKS_CREATED",
  GET_REFERRAL = "GET_REFERRAL",
  GET_TASKS_ASSIGN = "GET_TASKS_ASSIGN",
  GET_NEW_TASK = "GET_NEW_TASK",

  // SURVEY
  GET_SURVEY_BY_ID = "GET_SURVEY_BY_ID",

  // CHAT
  GET_USER_CHATS = "CHAT.GET_USER_CHATS",
  GET_USER_CHAT_BY_RECEIVER = "CHAT.GET_USER_CHAT_BY_RECEIVER",
  GET_CHAT_MESSAGES = "CHAT.GET_CHAT_MESSAGES",
  GET_CHAT_STATUS = "CHAT.GET_CHAT_STATUS",

  // WORK TIME
  GET_WORK_TIME_SESSIONS = "WORK_TIME.GET_WORK_TIME_SESSIONS",
}
